Rudimentary way to link to files.
oleeskild/digitalgarden pull request #122
Opened 2023-04-08 13:04 UTC by Mogyula

Hi!

This is my very first pull request sent to any project ever; I hope this is how it works. :)

So it was when I deployed a Digital Garden based on an Obsidian vault that references a ton of locally saved PDFs (as to support ideation for a reasearch project) that I realized that these wouldn't work online, as the plugin wouldn't commit ordinary files, only notes and images I guess.

Now I didn't do any work on the plugin, but I came to realize that if I just commit those PDFs manually, and also apply these changes to the codebase, then they'd be accessible.

The change on the regexp in .eleventy.js:160 is to cosnider links with or without the pipeline symbol, because I've noticed that notes' links get converted to the labeled format as in [[Another page|Another page]] even if in Obsidian it was just [[Another page]]. With PDFs though, you get [[dummy.pdf]] without the pipe.

See [this](https://digitalgarden-ten-weld.vercel.app/) site for a demo.

Gyula

2023-05-22 15:18 UTC, oleeskild requested changes
Sorry for being so slow reviewing this. I've added some comments on things that needs to be changed for this to be able to be merged in.

2023-05-22 15:18 UTC, oleeskild commented on .eleventy.js
> +        if (fileLink.slice(-5).includes(".") && fileLink.slice(-3)!=".md"){
Why does slice(-5).includes(".") imply its a file? This seems to only work with filetypes that have an extension that is smaller than 5 characters.

2023-05-22 15:18 UTC, oleeskild commented on src/site/notes/Another page.md
This file need to be removed before this PR can be merged.

2023-05-22 15:18 UTC, oleeskild commented on src/site/notes/Dummy page.md
This file need to be removed before this PR can be merged.

2023-05-22 15:18 UTC, oleeskild commented on src/site/etc/dummy.pdf
This file need to be removed before this PR can be merged.

2023-06-10 20:17 UTC, Mogyula commented
Sorry on my part as well for getting back to this with such a delay. I believe the requested changes have been made. Let me know otherwise.

2024-08-14 19:12 UTC, closed without merging